import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-neutral-950 text-neutral-100 min-h-screen font-sans">
        <header className="border-b border-neutral-800 py-4 px-6 flex items-center justify-between">
          <span className="text-xl font-bold tracking-tight">Memory AI</span>
        </header>
        <main className="max-w-2xl mx-auto py-8 px-4">
          {children}
        </main>
      </body>
    </html>
  )
}
